config/routes.rb
Heyhangman::Application.routes.draw do
  resources :hangmen

  resources :words

  get "landing/index"

  root 'landing#index'

  

end

app/models/hangman.rb
class Hangman
  include MongoMapper::Document

  key :word, String

end

app/models/word.rb
class Word
  include MongoMapper::Document

  key :word, String

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hangmen_controller.rb
class HangmenController < ApplicationController
  before_action :set_hangman, only: [:show, :edit, :update, :destroy]

  # GET /hangmen
  # GET /hangmen.json
  def index
    #@hangmen = Hangman.all

    #Pulling words from the db needs to be done in a more efficient manner
    @words = Word.all
    @word = @words[Random.rand(@words.size)].word.to_s
    
    #Generate the line of underscores
    @char_line = generate_line @word
    

  end

  # GET /hangmen/1
  # GET /hangmen/1.json
  def show
  end

  # GET /hangmen/new
  def new
    @hangman = Hangman.new
  end

  # GET /hangmen/1/edit
  def edit
  end

  # POST /hangmen
  # POST /hangmen.json
  def create
    @hangman = Hangman.new(hangman_params)

    respond_to do |format|
      if @hangman.save
        format.html { redirect_to @hangman, notice: 'Hangman was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hangman }
      else
        format.html { render action: 'new' }
        format.json { render json: @hangman.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hangmen/1
  # PATCH/PUT /hangmen/1.json
  def update
    respond_to do |format|
      if @hangman.update(hangman_params)
        format.html { redirect_to @hangman, notice: 'Hangman was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hangman.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hangmen/1
  # DELETE /hangmen/1.json
  def destroy
    @hangman.destroy
    respond_to do |format|
      format.html { redirect_to hangmen_url }
      format.json { head :no_content }
    end
  end

  def generate_line word
    i = 0
    line = ""
    while i < word.length
      line += "_ "
      i+=1
    end
    return line
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hangman
      @hangman = Hangman.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hangman_params
      params.require(:hangman).permit(:word)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render action: 'show', status: :created, location: @word }
      else
        format.html { render action: 'new' }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:word)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hangmen_helper.rb
module HangmenHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/hangmen/_form.html.erb
<%= form_for(@hangman) do |f| %>
  <% if @hangman.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hangman.errors.count, "error") %> prohibited this hangman from being saved:</h2>

      <ul>
      <% @hangman.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hangmen/edit.html.erb
<h1>Editing hangman</h1>

<%= render 'form' %>

<%= link_to 'Show', @hangman %> |
<%= link_to 'Back', hangmen_path %>

app/views/hangmen/index.html.erb
<h1>Listing hangmen</h1>

<h2>Word: <%= @word %></h2>
<h2>Char Line: <%= @char_line %></h2>
<input type="text" placeholder="Your guess" id="user-guess"><input type="button" onclick="readWord()" value="Guess!">
<br>

<script type="text/javascript">
	function readWord(){
		var word = "<%= @word %>";
		main(word);
	}
</script>

<%= link_to 'New Hangman', new_hangman_path %>

app/views/hangmen/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', hangmen_path %>

app/views/hangmen/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @hangman.word %>
</p>

<%= link_to 'Edit', edit_hangman_path(@hangman) %> |
<%= link_to 'Back', hangmen_path %>

app/views/landing/index.html.erb
<h1>Landing#index</h1>
<p>Find me in app/views/landing/index.html.erb</p>
<p>Landing page</p>
<%= link_to "Start a New Game", hangmen_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Heyhangman</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1>Listing words</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.word %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @word.word %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>